### ISSUE TITLE
Issue with traverse

### ISSUE THREAD

**Issue by Gonzih** [kachayev/muse#4]
Hello, I'm playing around with this library and I got stuck trying to reproduce traverse example.

```clojure
(defrecord Country [iso-id]
  DataSource
  (fetch [_] (api-get (str "countries/" iso-id))))

(defrecord Region [country-iso-id url-id]
  DataSource
  (fetch [_] (api-get (str "countries/" country-iso-id "/" url-id))))

(->> (Country. "es")
     (fmap :regions)
     (traverse #(Region. "es" (:code %)))
     run!!)
```

With this code snippet I'm getting folowing error:

```text
Exception in thread "async-dispatch-26" java.lang.IllegalArgumentException: No implementation of method: :done? of protocol: #'muse.core/MuseAST found for class: muse_playground.core.Region
```

Am I missing something here? Should I implement some additional protocols on my records?
Thanks!

**Comment by kachayev** [comment]
Unfortunately, I can't reproduce it:

```clojure
user=> (require '[muse.core :refer :all])
nil
user=> (require '[clojure.core.async :as a])
nil
user=> (defrecord Country [iso-id] DataSource (fetch [_] (go {:regions [{:code 1} {:code 2} {:code 3}]})))
user.Country
user=> (defrecord Region [country-iso-id url-id] DataSource (fetch [_] (a/go (inc url-id))) LabeledSource (resource-id [_] url-id))
user.Region
user=> (run!! (->> (Country. "es") (fmap :regions) (traverse #(Region. "es" (:code %)))))
[2 3 4]
user=> (->> (Country. "es") (fmap :regions) (traverse #(Region. "es" (:code %))) run!!)
[2 3 4]
```

Note, that I added `LabeledSource` to `Region`, but it doesn't make a difference with respect to exception that you've got.

Can you, please, provide more information:
* version of `muse`, `clojure` and `core.async` that you use
* import statement from current file

**Comment by kachayev** [comment]
@Gonzih I ran few more tests. And in few scenarios when cache id = nil (as you have) it can throw `IllegalArgumentException` exception. As it's non-deterministic and hard to debug, I will update library to use explicit `assert` that both resource name and resource ID are resolvable. 

In you case, `muse` library can calculate names: `Country` & `Region`, but IDs are not specified.

You can fix this as following:

```clojure
user=> (defrecord Country [iso-id] DataSource (fetch [_] (go {:regions [{:code 1} {:code 2} {:code 3}]})) LabeledSource (resource-id [_] iso-id))
user.Country
user=> (defrecord Region [country-iso-id url-id] DataSource (fetch [_] (a/go (inc url-id))) LabeledSource (resource-id [_] (str country-iso-id "//" url-id)))
user.Region
```

**Comment by Gonzih** [comment]
Yes, I was able to figure out that resources in traverse are cached very agressively. LabaledResource seems to be working, thanks! Aparetntly I wasn't reading readme very carefuly :) Sorry about that.

**Comment by Gonzih** [comment]
Also small followup question; Is it possible to use result of traverse in cats.core/mlet?

**Comment by kachayev** [comment]
@Gonzih, like this?

```clojure
user=> (run!! (m/mlet [regions (->> (Country. "es") (fmap :regions) (traverse #(Region. "es" (:code %))))] (m/return (count regions))))
3
```

**Comment by Gonzih** [comment]
Not exactyl, something like that:

```clojure
(run!! (m/mlet [country (Country. "es")
                full-regions (traverse #(Region. (:code country)
                                                 (:code %))
                                       (:regions country))]
               (m/return (assoc country :regions full-regions))))
```

**Comment by Gonzih** [comment]
Still can't figure out how to use traverse and preserve original country monad to reuse it later.

**Comment by kachayev** [comment]
That's a bit tricky... You have to know really well what's going on inside `mlet` to deal with it:

```clojure
user=> (defrecord Country [id] DataSource (fetch [_] (go {:regions [{:code 1} {:code 2} {:code 3}]})))
user.Country
user=> (defrecord Region [country-iso-id id] DataSource (fetch [_] (go (inc id))))
user.Region
user=> (run!! (m/mlet [country (Country. "es")
                                    regions (collect (map #(Region. "es" (:code %)) (:regions country)))]
                (m/return (count regions))))
3
```

**Comment by kachayev** [comment]
@Gonzih does it make sense? Or should I provide further explanation?

**Comment by Gonzih** [comment]
Yes, this makes sense. My last question is how collect works?
Thanks for  your patience :)

**Comment by kachayev** [comment]
`collect` takes a seq of MuseAST nodes (or resources to fetch) and convert them to a single MuseAST node. Definition with `scala` type system will look like following:

```scala
def collect[A](fs: Seq[MuseAST[A]]): MuseAST[Seq[A]]
```

**Comment by Gonzih** [comment]
Makes sense now, thank you!

**Comment by kachayev** [comment]
You are welcome!
