### ISSUE TITLE
Clojurescript port

### ISSUE THREAD

**Issue by tvanhens** [kachayev/muse#5]
I've started on a clojurescript port using cljc but I'm getting stuck trying to use the run! macro from clojurescript.

https://github.com/tvanhens/muse/blob/master/test/muse/test/cats.cljc#L50

Thats been the first hurdle. Will come back to it later but wanted to see if anyone could spot anything glaringly wrong.

I followed the advice here

http://stackoverflow.com/questions/29914967/can-cljc-single-file-macro-definitions-to-work-with-clojurescript

But with no success :(

**Comment by kachayev** [comment]
@tvanhens StackOverflow discussion that you shared describes reader conditionals. They are supported by Clojure 1.7 only, `muse` requires Clojure 1.6 instead.

**Comment by tvanhens** [comment]
Are there any plans to upgrade to 1.7 now that it's been officially released?

**Comment by kachayev** [comment]
@tvanhens I don't really want to rush with Clojure 1.7, it's not critical here and ClojureScript support can be added without conditional reading.

**Comment by kachayev** [comment]
I pushed few experiments to (feature-clojurescript)[https://github.com/kachayev/muse/tree/feature-clojurescript] branch. It can't compile test suites just now, but it can cross-compile `muse.core`. I'll finish with test cases soon.

**Comment by kachayev** [comment]
Now it works pretty well from ClojureScript code, with few differences/limitations describe in [README](https://github.com/kachayev/muse/tree/feature-clojurescript#clojurescript). I'll take few more days to stabilize this version and will merge it to master.

**Comment by tvanhens** [comment]
@kachayev very cool, thanks :)

**Comment by kachayev** [comment]
@tvanhens I think I can close this issue as far as ClojureScript support is merged into master and deployed on Clojars. Give me a shot if there is something that I missed!
